import { VertexAI } from '@google-cloud/vertexai';
import { logger } from '../../lib/logger';
import { logUsage } from '../usage';

// Configuration
const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || 'realness-score';
const LOCATION = 'us-central1';
const MODEL_NAME = 'gemini-2.0-flash-001'; // Latest stable Flash model (Feb 2025)

export async function generateContent(prompt: string): Promise<string> {
  try {
    logger.info(`Initializing Vertex AI for project ${PROJECT_ID} in ${LOCATION} with model ${MODEL_NAME}`);
    
    const vertex_ai = new VertexAI({project: PROJECT_ID, location: LOCATION});
    const model = vertex_ai.getGenerativeModel({
      model: MODEL_NAME,
      generationConfig: {
        'maxOutputTokens': 2048,
        'temperature': 0.7,
        'topP': 0.8,
      },
    });

    logger.info(`Sending prompt to Gemini: ${prompt.substring(0, 50)}...`);

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
    });

    const response = result.response;
    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      throw new Error('No content generated by Gemini');
    }

    await logUsage('text', 0.001, { promptLength: prompt.length, responseLength: text.length });

    return text;
  } catch (error) {
    logger.error('Gemini internal error:', error);
    throw error;
  }
}
